version: '3.8'
services:
  backend:
    image: backend:appImages
    build:
      context: ./model
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    container_name: back-container
    volumes:
      - ./model:/api

  frontend:
    image: frontend:appImages
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
    - 8501:8501
    depends_on:
      - backend
    container_name: front-container
    volumes:
      - ./front:/dashboard

